version: '3'
volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

services:
  redis:
    image: redis
    volumes:
      - redis-data:/var/lib/redis
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=envoyTest1
      - POSTGRES_USER=envoyTest1
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    image: envoy/ruby
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
